#!/usr/bin/with-contenv bash
# shellcheck shell=bash
function log() {
    echo "[Mount] ${1}"
}
# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086
umask 022
phpfpm_command="php-fpm7 -F"
log "-> Starting php-fpm <-"
exec s6-setuidgid abc $phpfpm_command