#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086
function log() {
    echo "[Mount] ${1}"
}
IFS=$'\n'
filter="$1"
config=/config/rclone.conf
#rclone listremotes | gawk "$filter"
mapfile -t mounts < <(eval rclone listremotes --config=${config} | grep "$filter" | sed -e 's/[GDSA00-99C:]//g' | sed '/^$/d')
## function source end

if [[ "$(command -v fusermount | wc -l)" != "1" ]]; then
   apk add fuser fuse-dev -q 
   log " > fuser and fusermount reinstalled "
fi

log "-> stoping mounts <-"
for i in ${mounts[@]}; do
    log "-> Stop Mounting $i <-"
    fusermount -uz $i
	sleep 2
	find /mnt/drive-* -type d -empty -delete
	sleep 2
done
sleep 10