#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086

umask 022
startup_mounts="/app/startupp-mounts.sh"
sleep 5s

echo "-> Starting mounts <-"
exec $startup_mounts