#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
    echo "[Mount] ${1}"
}
log "Shutting Down mergerfs Mount"
fusermount -uz /mnt/unionfs
log "Shutting Down Mount"
fusermount -uz /mnt/unionfs