#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086
function log() {
    echo "[Mount] ${1}"
}
umask 022
mount_command="/app/mergerfs.sh"
sleep 5

log "-> Starting mergerfs <-"
exec $mount_command