#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086
function log() {
    echo "[Mount] ${1}"
}
pids="$(ps -ef | grep 'remotecleanup.sh' | head -n 1 | grep -v grep | awk '{print $1}')"
if [ "$pids" != "" ]; then
  kill -15 $pids
  sleep 2
fi
