#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086
function log() {
    echo "[Mount] ${1}"
}
umask 022
check_mounts="/app/checkmounts.sh"
sleep 5

log "-> Starting Check Mounts <-"
exec $check_mounts
