#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
echo "[MOUNT] ${1}"
}

apk add --quiet --no-cache --no-progress wget curl bash unzip rclone

log "*** checking rclone.conf"
while [ ! -f "/config/rclone.conf" ]; do
   log "-->> [ WARNING ] ------------------------- [ WARNING ] <<--"
   log "-->> [ WARNING ] no rclone.conf file found [ WARNING ] <<--"
   log "-->> [ WARNING ]       sleeping for 30s    [ WARNING ] <<--"
   log "-->> [ WARNING ] ------------------------- [ WARNING ] <<--"
   sleep 30 
done

log "-> Copying rclone.conf <-"
    mkdir -p /config/{rclone,env,discord,logs,rc-purge,rc-refresh,scripts}
    rm -f /config/rclone/rclone-docker.conf
    find /config -name "rclone.conf" -type f -exec cp {} /config/rclone/rclone-docker.conf \;
    log "-> Make needed edits to rclone-docker.conf <-"
    sed -i "s#/opt/appdata/plexguide/.blitzkeys/#/config/keys/#g" /config/rclone/rclone-docker.conf
    sed -i "s#/opt/appdata/uploader/#/config/keys/#g" /config/rclone/rclone-docker.conf
    sed -i "s#/opt/appdata/services/uploader/keys/#/config/keys/#g" /config/rclone/rclone-docker.conf
    sed -i "s#/opt/uploader/keys/#/config/keys/#g" /config/rclone/rclone-docker.conf
    sed -i '/pgunion/{n;N;d;}' /config/rclone/rclone-docker.conf
    sed -i '/pgunion/d' /config/rclone/rclone-docker.conf
    sed -i "s#rotate 4#rotate 1#g" /etc/logrotate.conf
    sed -i "s#weekly#daily#g" /etc/logrotate.conf
log "-> rclone_docker.conf edits done <-"
#<EOF>#
