#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
echo "[Mount] ${1}"
}
if [ ! -f "/config/rclone.conf" ]; then
   log "-->> [ WARNING ] no rclone.conf file found [ WARNING ] <<--"
   sleep 60
   exit 0
fi
if [ ! -d "/config/rclone/" ]; then 
   mkdir -p /config/rclone 
fi
if [ -f "/config/rclone.conf" ]; then
    log "-> Copying rclone.conf <-"
        rm -f /config/rclone/rclone-docker.conf
        cp /config/rclone.conf /config/rclone/rclone-docker.conf
    log "-> Make needed edits to rclone-docker.conf <-"
        sed -i "s#/opt/appdata/plexguide/.blitzkeys/#/config/keys/#g" /config/rclone/rclone-docker.conf
        sed -i "s#/opt/appdata/uploader/#/config/keys/#g" /config/rclone/rclone-docker.conf
        sed -i "s#/opt/appdata/services/uploader/keys/#/config/keys/#g" /config/rclone/rclone-docker.conf
        sed -i "s#/opt/uploader/keys/#/config/keys/#g" /config/rclone/rclone-docker.conf
        sed -i '/pgunion/{n;N;d;}' /config/rclone/rclone-docker.conf
        sed -i '/pgunion/d' /config/rclone/rclone-docker.conf
    log "-> rclone_docker.conf edits done <-"
fi
log "-> install rclone || start <-"
    apk add unzip bash curl --quiet
    wget --quiet https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip -O rclone.zip && \
    unzip -q rclone.zip && rm rclone.zip && \
    mv rclone*/rclone /usr/bin && rm -r rclone*
log "-> install rclone || done <-"
#<EOF>#
