#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
## function source
function log() {
echo "[Mount] ${1}"
}
log "-> Setting Permissions || start <-"
chown -hR abc:abc /root
find /config -exec chmod a=rx,u+w {} \;
find /config -exec chown -hR abc:abc {} \;
find /app -exec chmod a=rx,u+w {} \;
find /app -exec chown -hR abc:abc {} \;

if [[ $(command -v rclone | wc -l) == "1" ]]; then
    chown -cf abc:abc /root
fi
log "-> Setting Permissions || done <-"
#EOF
