#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
## function source
function log() {
echo "[Mount] ${1}"
}
log "-> Setting Permissions || start <-"

folder="/config /app /root"

for i in ${folder}; do
  find $i -exec chmod a=rx,u+w {} \;
  find $i -exec chown -hR abc:abc {} \;
  chown -cf abc:abc /root
done

log "-> Setting Permissions || done <-"

#find /app -exec chmod a=rx,u+w {} \;
#find /app -exec chown -hR abc:abc {} \;
#mkdir -p /var/lib/nginx/logs/
#if [[ $(command -v rclone | wc -l) == "1" ]]; then
#    chown -cf abc:abc /root
#fi
#log "-> Setting Permissions || done <-"
#EOF
