#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
DIR_CACHE_TIME=${DIR_CACHE_TIME:-2m}
VFS_READ_CHUNK_SIZE=${VFS_READ_CHUNK_SIZE:-96M}
VFS_CACHE_MAX_AGE=${VFS_CACHE_MAX_AGE:-675h}
VFS_READ_CHUNK_SIZE_LIMIT=${VFS_READ_CHUNK_SIZE_LIMIT:-1G}
VFS_CACHE_MODE=${VFS_CACHE_MODE:-writes}
VFS_CACHE_MAX_SIZE=${VFS_CACHE_MAX_SIZE:-10G}
BUFFER_SIZE=${BUFFER_SIZE:-48M}
RC_ENABLED=${RC_ENABLED:-false}
RC_ADDR=${RC_ADDR:-0.0.0.0:25975}
RC_USER=${RC_USER:-user}
RC_PASS=${RC_PASS:-xxx}
POLL_INTERVAL=${POLL_INTERVAL:-5m}
LOGLEVEL=${LOGLEVEL:-INFO}
UAGENT=${UAGENT:-somerandstring}

function envs() {
echo "
   DOCKER ENV vars
-------------------------------------------------------
   TimeZone                       ${TZ}
   DISCORD_EMBED_TITEL            ${DISCORD_EMBED_TITEL}
   DISCORD_NAME_OVERRIDE          ${DISCORD_NAME_OVERRIDE}
   DIR_CACHE_TIME                 ${DIR_CACHE_TIME:-2m}
   VFS_READ_CHUNK_SIZE            ${VFS_READ_CHUNK_SIZE:-96M}
   VFS_CACHE_MAX_AGE              ${VFS_CACHE_MAX_AGE:-675h}
   VFS_READ_CHUNK_SIZE_LIMIT      ${VFS_READ_CHUNK_SIZE_LIMIT:-1G}
   VFS_CACHE_MODE                 ${VFS_CACHE_MODE:-writes}
   VFS_CACHE_MAX_SIZE             ${VFS_CACHE_MAX_SIZE:-10G}
   BUFFER_SIZE                    ${BUFFER_SIZE:-48M}
   RC_ENABLED                     ${RC_ENABLED:-false}
   RC_ADDR                        ${RC_ADDR:-0.0.0.0:25975}
   RC_USER                        ${RC_USER:-user}
   RC_PASS                        ${RC_PASS:-xxx}
   POLL_INTERVAL                  ${POLL_INTERVAL:-5m}
   LOGLEVEL                       ${LOGLEVEL:-INFO}
-------------------------------------------------------
"
}
DEBUG=${DEBUG:-false}
if [ "${DEBUG}" == 'false' ]; then
 envs
 sleep 5
else
 envs
 sleep 60
fi
