#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
echo "[Mount] ${1}"
}
rm -rf /tmp/mergerfs_version && rm -rf /tmp/mergerfs
curl -sX GET "https://api.github.com/repos/trapexit/mergerfs/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]' > /tmp/mergerfs_version && \
log "-> Install now MergerFS Version `cat /tmp/mergerfs_version` <-"
apk --quiet --no-cache --no-progress add \
    fuse libattr libstdc++ autoconf automake \
    libtool gettext-dev attr-dev linux-headers make build-base \
    fuse libattr libstdc++ git

apk --no-cache update --quiet && apk --no-cache upgrade --quiet && apk --no-cache fix --quiet && rm -rf /var/cache/apk/*

git clone --quiet https://github.com/trapexit/mergerfs.git /tmp/mergerfs 1>/dev/null 2>&1 && cd /tmp/mergerfs && \
    git checkout --quiet `cat /tmp/mergerfs_version` -b local && make STATIC=1 LTO=1 1>/dev/null 2>&1 && make install 1>/dev/null 2>&1
    cp /usr/local/bin/mergerfs /usr/bin/mergerfs 1>/dev/null 2>&1
    cp /usr/local/bin/mergerfs-fusermount /usr/bin/mergerfs-fusermount 1>/dev/null 2>&1
    cp /sbin/mount.mergerfs /sbin/mount.mergerf 1>/dev/null 2>&1

mgstored="$(mergerfs -v | grep 'mergerfs version:' | awk '{print $3}')"
log "-> Installed MergerFS Version $mgstored <-"

log "-> Configure MergerFS|| start <-"
    sed -i 's/#user_allow_other/user_allow_other/' /etc/fuse.conf
log "-> Configure Mergerfs || done <-"
#>EOF<#
