#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
echo "[Mount] ${1}"
}
mergerfs=$(command -v mergerfs | wc -l)
if [ "${mergerfs}" != "1" ]; then
    log "-> Enabled MergerFS <-"
    log "-> configure mergerfs || start <-"
      apk --no-cache add --quiet --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing mergerfs
      apk --no-cache update -qq && apk --no-cache upgrade -qq && apk --no-cache fix -qq
      sed -i 's/#user_allow_other/user_allow_other/' /etc/fuse.conf
      rm -rf /var/cache/apk/*
    log "-> configure mergerfs || done <-"
fi

 
