#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
echo "[Mount] ${1}"
}
log "-> Install MergerFS <-"
log "-> Configure MergerFS || start <-"
apk --no-cache add --quiet --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing mergerfs
apk --quiet --no-cache --no-progress add fuse fuse-dev
apk --no-cache update --quite && apk --no-cache upgrade --quite && apk --no-cache fix --quite
log "-> configure mergerfs || start <-"
sed -i 's/#user_allow_other/user_allow_other/' /etc/fuse.conf
rm -rf /var/cache/apk/*
log "-> Configure Mergerfs || done <-"
#>EOF<#
