#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
echo "[Mount] ${1}"
}
cron=/tmp/crontab.conf
if [ -f ${cron} ]; then
   rm -f ${cron}
   log "-> update packages || start <-" 
   apk --no-cache update -qq && apk --no-cache upgrade -qq && apk --no-cache fix -qq
  echo -e "## update alpine weekly
@weekly bash /app/update-alpine/update-alpine.sh \
## update drive size daily
@daily bash /app/mountsize/mountsize.sh" >> /tmp/crontab.conf
   crontab /tmp/crontab.conf
   rm -rf /var/cache/apk/*
   log "-> update packages || done <-"
fi
sleep 5
#>EOF<#
